# Generated by Django 3.2.9 on 2021-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='graduate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
