# Generated by Django 3.2.9 on 2021-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_students_graduate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.AddField(
            model_name='students',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=150),
        ),
    ]
