# Generated by Django 3.2.9 on 2021-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_rename_filed_courses_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='field',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
