# Generated by Django 3.2.9 on 2021-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_courses_fields_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='father_birthday',
            field=models.DateField(null=True),
        ),
    ]
