# Generated by Django 3.2.9 on 2021-11-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_students_father_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father_birthday',
            field=models.DateField(),
        ),
    ]
