# Generated by Django 3.2.9 on 2021-11-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_students_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father_birthday',
            field=models.IntegerField(),
        ),
    ]
